carthorse:
  version-from: setup.py
  tag-format: "{version}"
  when:
    - version-not-tagged
  actions:
    - run: "pip install -e .[release]"
    - run: "twine upload -u __token__ -p $PYPI_TOKEN dist/*"
    - create-tag
